name: alphafold2
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - openmm=7.6
  - pdbfixer=1.8
  - cudnn=8.2
  - cudatoolkit=11.1
  - cudatoolkit-dev=11.1
  - numpy=1.19
  - scipy=1.7
  - pandas=1.3
  - biopython=1.79
  - absl-py=0.13
  - chex=0.0.7
  - dm-haiku=0.0.4
  - dm-tree=0.1.6
  - jax=0.2.14
  - protobuf==3.20.1
  - immutabledict=2.0
  - bioconda::hmmer=3.3
  - bioconda::hhsuite=3.3
  - bioconda::kalign2=2.04
  - psutil
  - joblib
  - pip
  - pip:
      - ml-collections==0.1.0
      - tensorflow==2.5.0
